version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: taskmanager-mongodb
    ports:
      - \"27017:27017\"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - taskmanager-network

  redis:
    image: redis:7-alpine
    container_name: taskmanager-redis
    ports:
      - \"6379:6379\"
    networks:
      - taskmanager-network

  backend-blue:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: backend-blue
    ports:
      - \"3001:3000\"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/taskmanager?authSource=admin
      - REDIS_URL=redis://redis:6379
      - APP_VERSION=blue-local
      - APP_COLOR=blue
    depends_on:
      - mongodb
      - redis
    networks:
      - taskmanager-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  backend-green:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile  
    container_name: backend-green
    ports:
      - \"3002:3000\"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/taskmanager?authSource=admin
      - REDIS_URL=redis://redis:6379
      - APP_VERSION=green-local
      - APP_COLOR=green
    depends_on:
      - mongodb
      - redis
    networks:
      - taskmanager-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: frontend
    ports:
      - \"8080:8080\"
    environment:
      - BACKEND_URL=http://backend-blue:3000
      - NODE_ENV=development
    depends_on:
      - backend-blue
    networks:
      - taskmanager-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    container_name: nginx-loadbalancer
    ports:
      - \"80:80\"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend-blue
      - backend-green
      - frontend
    networks:
      - taskmanager-network

volumes:
  mongodb_data:

networks:
  taskmanager-network:
    driver: bridge
