apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
    version: blue  # Default to blue environment
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
